# Theme
theme: minima

# Metadata
title: ughe.github.io
author: William Ughetta
github_username:  ughe

permalink: /:year/:month/:day/:title
show_excerpts: false
plugins:

# Markdown style
kramdown:
  input: GFM
  auto_ids: true

# Include a dotfile
#include: ["data/2022/.dotfile"]

